/* generated by /Users/bryan/Desktop/github_repos/AIOS/deps/seL4_tools/elfloader-tool/../cmake-tool/helpers/platform_sift.py BEGIN */
int num_memory_regions = 1;

struct memory_region {
    size_t start;
    size_t end;
} memory_region[1] = {
	{ .start = 1073741824, .end = 2147483648 },
};
/* generated by /Users/bryan/Desktop/github_repos/AIOS/deps/seL4_tools/elfloader-tool/../cmake-tool/helpers/platform_sift.py END */
