#!/bin/sh
# tools/bump_build.sh — increment build number and emit C header
#
# Usage:  sh tools/bump_build.sh          (from project root)
# Reads:  .build_number
# Writes: include/aios/build_number.h     (auto-generated, .gitignore it)
#         .build_number                    (updated counter)

FILE=".build_number"
HEADER="include/aios/build_number.h"

# Read current number (default to 0 if missing)
if [ -f "$FILE" ]; then
    N=$(cat "$FILE" | tr -d '[:space:]')
else
    N=0
fi

# Increment
N=$((N + 1))

# Write back
echo "$N" > "$FILE"

# Generate header
cat > "$HEADER" << HDR
/* Auto-generated by tools/bump_build.sh — do NOT edit */
#ifndef _AIOS_BUILD_NUMBER_H
#define _AIOS_BUILD_NUMBER_H
#define AIOS_BUILD_NUMBER $N
#define AIOS_BUILD_DATE   "$(date -u '+%Y-%m-%d %H:%M:%S UTC')"
#endif
HDR

echo "  Build #${N} — $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
