#!/bin/sh
# mkaiosroot.sh -- build an AIOS root filesystem: the self-contained world a confined AIOS guest sees.
#
# AIOS is a userspace kernel (it runs as a process on the host Linux), so this is NOT a bootable
# kernel image -- it is the AIOS USERLAND: the AIOS-ABI binaries + config that the AIOS kernel serves
# and CONFINES. Launched with AIOS_ROOT set, every guest path resolves inside this tree
# (openat2 RESOLVE_IN_ROOT) and a guest can only exec binaries inside it, so the shell + utilities see
# only this image, never the host filesystem.
#
# Run the resulting image as a confined AIOS system. NOTE: the INIT binary is the trusted entry and is
# loaded by its HOST path (so name the image's shell by its real path); every path the shell resolves
# AFTER that is confined to AIOS_ROOT.
#   AIOS_ROOT="$PWD/aiosroot" PATH=/bin ./aios-uk "$PWD/aiosroot/bin/sh"
# or ship it: the script also writes aiosroot.tar (untar onto any host, point AIOS_ROOT at it).
set -eu

UK=$(cd "$(dirname "$0")" && pwd)
ROOT="${1:-$UK/aiosroot}"

# the binaries must be built first (make all)
test -x "$UK/dash" || { echo "build first: make all (need ./dash + ./sbase-*)" >&2; exit 1; }

rm -rf "$ROOT"
mkdir -p "$ROOT/bin" "$ROOT/sbin" "$ROOT/etc" "$ROOT/tmp" "$ROOT/home/aios"

# the shell: dash as /bin/sh AND /bin/dash
cp "$UK/dash" "$ROOT/bin/dash"
cp "$UK/dash" "$ROOT/bin/sh"

# the coreutils (vendored sbase, built as sbase-<name>) installed at their standard names
for u in true false echo cat wc mkdir rm ls head tail cp mv ln chmod sort grep \
         whoami logname uname env printenv pwd tty date tr cut seq printf; do
	cp "$UK/sbase-$u" "$ROOT/bin/$u"
done

# the SYSTEM LAYER (increment 1): the AIOS init + login. The appliance launches /sbin/init, which
# respawns /bin/login (prompt -> /etc/shadow auth -> the user's login shell).
cp "$UK/init"  "$ROOT/sbin/init"
cp "$UK/login" "$ROOT/bin/login"

# the shutdown command: one binary under three names in /sbin (it picks the action from argv[0]).
# `poweroff`/`halt`/`reboot` ask the AIOS kernel to bring the system down (root only).
for n in poweroff halt reboot; do cp "$UK/poweroff" "$ROOT/sbin/$n"; done

# the system hostname (uname -n / the login banner read this; AIOS reports its OWN identity, not the host)
echo aios > "$ROOT/etc/hostname"

# a minimal passwd/group database (so ls -l and grep show real names inside the image)
cat > "$ROOT/etc/passwd" <<'EOF'
root:x:0:0:root:/:/bin/sh
aios:x:1000:1000:AIOS user:/home/aios:/bin/sh
EOF
cat > "$ROOT/etc/group" <<'EOF'
root:x:0:
aios:x:1000:
EOF

# /etc/shadow: the login secrets, now SHA-512 ($6$) crypt HASHES (increment 2), byte-identical to
# `openssl passwd -6` -- AIOS's crypt() recomputes + compares them. Passwords stay aios/aios + root/root
# (the Pi convention); the salts are fixed so the hashes are reproducible. Generated by:
#   openssl passwd -6 -salt aiossalt aios   ;   openssl passwd -6 -salt rootsalt root
cat > "$ROOT/etc/shadow" <<'EOF'
root:$6$rootsalt$DMaW/SWhAWN4kO5JlNx8ozBbTvstA7SEpK23VKJsNNwPfGKtVkA28Khht9Dlhody/oJANee.ewEebcJXbvL.T1:::::::
aios:$6$aiossalt$RniFLmVGV7vaoLmNnMHSgLxQ0nTG4iNL61yVU3c6W09Df0xuSmUaFvd1PVx9YAX8BDudi0ZCyxsFu.qDWkqD3/:::::::
EOF
chmod 600 "$ROOT/etc/shadow"

# /etc/profile -- sourced by the login shell (dash, started with argv0 "-sh")
cat > "$ROOT/etc/profile" <<'EOF'
export PATH=/bin:/sbin
export PS1='\$ '
EOF

# a motd the login shows on a successful login
cat > "$ROOT/etc/motd" <<'EOF'
Welcome to AIOS -- a userspace kernel. This whole world is served + confined by aios-uk;
the host filesystem is invisible. Try: ls -l ;  grep root /etc/passwd ;  whoami-style id via getpwuid.
EOF

# a shippable archive of the image (an ext4 image is also possible: the host mounts it, then points
# AIOS_ROOT at the mountpoint -- AIOS confines via a dir fd, the host owns the actual filesystem).
( cd "$ROOT/.." && tar cf "$UK/aiosroot.tar" "$(basename "$ROOT")" )

echo "built AIOS root image:"
echo "  tree:    $ROOT  ($(find "$ROOT" -type f | wc -l | tr -d ' ') files, $(du -sh "$ROOT" 2>/dev/null | cut -f1))"
echo "  archive: $UK/aiosroot.tar"
echo "  run:     AIOS_ROOT=\"$ROOT\" PATH=/bin $UK/aios-uk \"$ROOT/bin/sh\""
