#!/usr/bin/env python3
"""
gen_getconf.py -- generate minimal getconf.h for sbase getconf.c
Produces lookup tables for sysconf, confstr, pathconf, and limits.
"""
import sys
import os

def main():
    outpath = sys.argv[1] if len(sys.argv) > 1 else None
    lines = []
    lines.append("/* Auto-generated by gen_getconf.py -- do not edit */")
    lines.append("")

    # sysconf variables (_SC_* from POSIX)
    sysconf_vars = [
        ("ARG_MAX", "_SC_ARG_MAX"),
        ("CHILD_MAX", "_SC_CHILD_MAX"),
        ("CLK_TCK", "_SC_CLK_TCK"),
        ("NGROUPS_MAX", "_SC_NGROUPS_MAX"),
        ("OPEN_MAX", "_SC_OPEN_MAX"),
        ("PAGESIZE", "_SC_PAGESIZE"),
        ("PAGE_SIZE", "_SC_PAGESIZE"),
        ("LINE_MAX", "_SC_LINE_MAX"),
        ("_POSIX_VERSION", "_SC_VERSION"),
        ("HOST_NAME_MAX", "_SC_HOST_NAME_MAX"),
        ("LOGIN_NAME_MAX", "_SC_LOGIN_NAME_MAX"),
        ("SYMLOOP_MAX", "_SC_SYMLOOP_MAX"),
    ]
    lines.append("static struct var sysconf_l[] = {")
    for name, val in sysconf_vars:
        lines.append('\t{ "%s", %s },' % (name, val))
    lines.append("};")
    lines.append("")

    # confstr variables (_CS_* -- most systems only have PATH)
    lines.append("static struct var confstr_l[] = {")
    lines.append('#ifdef _CS_PATH')
    lines.append('\t{ "PATH", _CS_PATH },')
    lines.append('#endif')
    lines.append("};")
    lines.append("")

    # pathconf variables (_PC_*)
    pathconf_vars = [
        ("LINK_MAX", "_PC_LINK_MAX"),
        ("NAME_MAX", "_PC_NAME_MAX"),
        ("PATH_MAX", "_PC_PATH_MAX"),
        ("PIPE_BUF", "_PC_PIPE_BUF"),
    ]
    lines.append("static struct var pathconf_l[] = {")
    for name, val in pathconf_vars:
        lines.append('\t{ "%s", %s },' % (name, val))
    lines.append("};")
    lines.append("")

    # limits (compile-time constants)
    limits_vars = [
        ("CHAR_BIT", "CHAR_BIT"),
        ("CHAR_MAX", "CHAR_MAX"),
        ("CHAR_MIN", "CHAR_MIN"),
        ("INT_MAX", "INT_MAX"),
        ("INT_MIN", "INT_MIN"),
        ("LONG_MAX", "LONG_MAX"),
        ("LONG_MIN", "LONG_MIN"),
        ("SCHAR_MAX", "SCHAR_MAX"),
        ("SCHAR_MIN", "SCHAR_MIN"),
        ("SHRT_MAX", "SHRT_MAX"),
        ("SHRT_MIN", "SHRT_MIN"),
        ("SSIZE_MAX", "SSIZE_MAX"),
        ("UCHAR_MAX", "UCHAR_MAX"),
        ("UINT_MAX", "(long)UINT_MAX"),
        ("ULONG_MAX", "(long)ULONG_MAX"),
        ("USHRT_MAX", "USHRT_MAX"),
    ]
    lines.append("static struct var limits_l[] = {")
    for name, val in limits_vars:
        lines.append('\t{ "%s", %s },' % (name, val))
    lines.append("};")
    lines.append("")

    out = "\n".join(lines) + "\n"
    if outpath:
        with open(outpath, "w") as f:
            f.write(out)
        print("Generated %s (%d bytes)" % (outpath, len(out)))
    else:
        sys.stdout.write(out)

if __name__ == "__main__":
    main()
