/* Auto-generated by tools/bump_build.sh — do NOT edit */
#ifndef _AIOS_BUILD_NUMBER_H
#define _AIOS_BUILD_NUMBER_H
#define AIOS_BUILD_NUMBER 822
#define AIOS_BUILD_DATE   "2026-04-02 03:00:28 UTC"
#endif
